// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea2_RegistroDeRoles.DAL;

namespace Tarea2_RegistroDeRoles.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210121065141_Incial")]
    partial class Incial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Tarea2_RegistroDeRoles.Entidades.Roles", b =>
                {
                    b.Property<int>("rolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("TEXT");

                    b.HasKey("rolesId");

                    b.ToTable("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
